### ISSUE TITLE
Image upload on facebook 'overspill chat' caused crash (debian 9)

### ISSUE THREAD

**Issue by nileplumb** [miscord/miscord#357] opened 2018-11-09 22:49 UTC
Been using a discord sync'd fb 'chat A' for a while, now the 'chat A' is full on FB side an 'overspill' linked chat "chat A+" was created, images often do not uploaded to "chat A+" but today a user managed to crash miscord by uploading an image directly to "chat A+"

Despite using pm2 miscord does not seem to auto-restart anymore either

below is the error code produced by this upload to the overspill "chat A+"

```
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at Object.module.exports [as discord] (/usr/lib/node_modules/miscord/lib/createMessage/fromMessenger.discord.js:10:117)
    at Promise.all.channels.map (/usr/lib/node_modules/miscord/lib/messenger/listener.js:36:48)
    at Array.map (<anonymous>)
    at ApiEmitter.module.exports (/usr/lib/node_modules/miscord/lib/messenger/listener.js:35:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
```

**Comment by Bjornskjald** [comment] 2018-11-14 20:21
Looks like it couldn't find the sender? Do you have more detailed logs? Can you reproduce that issue?

**Comment by Bjornskjald** [comment] 2018-12-13 14:56
Actually, a duplicate of #367, fixed.

**Closed by Bjornskjald** 2018-12-13 14:56 UTC
Labels: bug, needs testing
