### ISSUE TITLE
Miscord is no longer sending message to facebook

### ISSUE THREAD

**Issue by smieszkooo** [miscord/miscord#483] opened 2021-02-18 13:05 UTC
Miscord is no longer sending message to facebook. From facebook to discord it runs good.

OS: Windows 

Miscord 5.0.4

Config: 
```
{
  "messenger": {
    "username": "*****",
    "password": "******",
    "format": "[{username}] {source} {message}",
    "sourceFormat": {
      "discord": "(D)",
      "messenger": "(M - {name})"
    }
  },
  "discord": {
    "token": "*****",
    "showFullNames": true
  },
  "channels": {
    "command": "*****",
    "error": "******"
  }
}
```

**Comment by HansJK** [comment] 2021-02-21 20:02
Facebook changed their API, and it broke the Miscord bridge. With the lack of development on Miscord lately I wouldn't expect any fixes any time soon.

**Comment by ptrcnull** [comment] 2021-02-21 23:03
Well, I'm trying my best despite having no time and no other contributors to help.
Closing as duplicate of #482.

**Closed as completed by ptrcnull** 2021-02-21 23:03 UTC

**Comment by HansJK** [comment] 2021-02-22 03:43
Don't get me wrong, I'm not complaining. I know how difficult it can be to get enough time for personal projects.
